[book]
title = "Haskell for Rustaceans"
authors = ["thelissimus"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/haskelluz/haskell-for-rustaceans"
