[book]
title = "Haskell for Rustaceans"
authors = ["thelissimus"]
description = "A free handbook for introducing Rustaceans to Haskell."
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/haskelluz/haskell-for-rustaceans"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
